services:
  webapp:
    image: 'metadata-microservice-webapp:rc1'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'metadata-microservice-webapp'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8081:8080'
    expose:
      - '8000'
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/metadata_microservice_db
    secrets:
      - db_username
      - db_password
      - db_owner_username
      - db_owner_password
    healthcheck:
      # "curl --fail --silent localhost:8081/status | grep OK || exit 1"
      # TODO replace this silly thing with a command similar to the above, with wget
      test: "echo OK"
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: 'postgres:17.4'
    container_name: 'metadata-microservice-db'
    environment:
      - 'POSTGRES_DB=metadata_microservice_db'
      - 'POSTGRES_PASSWORD=local-dev-only'
      - 'POSTGRES_USER=metadata_owner'
    volumes:
      # init scripts, only run once on empty DB
      - ./src/test/resources/testdb-init:/docker-entrypoint-initdb.d:ro
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready --username=metadata_owner --dbname=metadata_microservice_db' ]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  db_username:
    file: ./src/test/resources/secrets/app_user_test
  db_password:
    file: ./src/test/resources/secrets/app_password_test
  db_owner_username:
    file: ./src/test/resources/secrets/owner_user_test
  db_owner_password:
    file: ./src/test/resources/secrets/owner_password_test
